# Generated by Django 3.1.7 on 2021-03-09 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loyaltypoints.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('img', models.ImageField(upload_to='pics')),
                ('discount_price', models.FloatField()),
                ('category', models.CharField(choices=[('N', 'Nuts'), ('O', 'Oils'), ('P', 'Pasta')], max_length=1)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='loyaltycoins',
            fields=[
                ('points_earned', models.FloatField()),
                ('points_redeem', models.IntegerField(default=0)),
                ('points_pending', models.IntegerField(default=0)),
                ('points_exp', models.DateTimeField(default=loyaltypoints.models.get_deadline)),
                ('point_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('total_points', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaltypoints.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_by', models.CharField(max_length=50)),
                ('mobileno', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0)),
                ('orderid', models.IntegerField(primary_key=True, serialize=False)),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyaltypoints.loyaltycoins')),
                ('products', models.ManyToManyField(to='loyaltypoints.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loyaltycoins',
            name='ord_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaltypoints.order'),
        ),
        migrations.AddField(
            model_name='loyaltycoins',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
