# Generated by Django 3.1.7 on 2021-03-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltycoins',
            name='ord_id',
        ),
    ]
