# Generated by Django 3.1.7 on 2021-03-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0002_remove_loyaltycoins_ord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltycoins',
            name='points_pending',
        ),
    ]
