# Generated by Django 3.1.7 on 2021-03-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0003_remove_loyaltycoins_points_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_address',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_details',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
