# Generated by Django 3.1.7 on 2021-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0005_order_orderrefid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='point',
        ),
        migrations.AddField(
            model_name='order',
            name='point',
            field=models.ManyToManyField(to='loyaltypoints.loyaltycoins'),
        ),
    ]
