# Generated by Django 3.1.7 on 2021-03-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0007_auto_20210310_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycoins',
            name='order_info',
            field=models.ManyToManyField(to='loyaltypoints.order'),
        ),
    ]
