# Generated by Django 3.1.7 on 2021-03-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0008_loyaltycoins_order_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
