# Generated by Django 3.1.7 on 2022-03-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0011_auto_20220314_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='loyaltypoints.orderitem'),
        ),
    ]
