# Generated by Django 3.1.7 on 2021-03-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0012_auto_20220314_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyaltycoins',
            old_name='point_status',
            new_name='point_exp_status',
        ),
    ]
