# Generated by Django 3.1.7 on 2021-03-16 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0015_auto_20210315_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltycoins',
            name='point_exp_status',
        ),
    ]
