# Generated by Django 3.1.7 on 2021-03-16 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0016_remove_loyaltycoins_point_exp_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltycoins',
            name='points_redeem',
        ),
    ]
