# Generated by Django 3.1.7 on 2021-03-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0017_remove_loyaltycoins_points_redeem'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycoins',
            name='points_redeem',
            field=models.IntegerField(default=0),
        ),
    ]
