# Generated by Django 3.1.7 on 2021-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0020_auto_20210320_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_address',
            field=models.CharField(max_length=500),
        ),
    ]
