# Generated by Django 3.1.7 on 2021-03-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0026_point_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_master',
            name='max_points',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='point_master',
            name='min_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
