# Generated by Django 3.1.7 on 2021-03-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0027_auto_20210325_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_master',
            name='min_redeem',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point_master',
            name='from_point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='point_master',
            name='max_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='point_master',
            name='min_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='point_master',
            name='percentage1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='point_master',
            name='percentage2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='point_master',
            name='to_point',
            field=models.IntegerField(),
        ),
    ]
