# Generated by Django 3.1.7 on 2021-03-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0028_auto_20210325_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_master',
            name='loyal',
            field=models.ManyToManyField(to='loyaltypoints.userprofile'),
        ),
    ]
