# Generated by Django 3.1.7 on 2021-03-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0029_point_master_loyal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point_master',
            name='loyal',
        ),
    ]
