# Generated by Django 3.1.7 on 2021-03-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0030_remove_point_master_loyal'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_master',
            name='point_conversion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
