# Generated by Django 3.1.7 on 2021-03-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0031_point_master_point_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.FloatField(blank=True, default=-1),
            preserve_default=False,
        ),
    ]
